version: "3"
services:
  php:
    build: 
      context: './php/'
    networks:
      - backend
    volumes:
      - ./../magento2/:/var/www/html/magento/
    container_name: php
  apache:
    build:
      context: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./../magento2/:/var/www/html/magento/
    container_name: apache
  mysql:
    build:
      context: './mysql/'
    env_file:
      - ./mysql/.env
    networks:
      - backend
    ports:
      - "3306:3306"
    container_name: mysql
networks:
  backend:
